---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)

library(ggplot2)
```

```{r}
dir <- getwd()
item_list_buys <- read.csv(paste(dir, "/gw2-all-buys.csv", sep = ""))
item_list_sells <- read.csv(paste(dir, "/gw2-all-sells.csv", sep = ""))
```


```{r}
nrow(item_list_buys)
item_list_buys %>% 
  select(name) %>% 
  drop_na() %>% 
  unique() %>% 
  count()

nrow(item_list_sells)
item_list_sells %>% 
  select(name) %>% 
  drop_na() %>% 
  unique() %>% 
  count()
```

We need to divide with 10.000 to display price in gold.
10.000 copper == 100 silver == 1 gold.

```{r}
item_list_sells_group <- item_list_sells %>% 
  group_by(name) %>% 
  summarise(unit_price = mean(unit_price), 
            vendor_value = mean(vendor_value),
            type = unique(type),
            rarity = unique(rarity))

item_list_sells_group %>% 
  ggplot() +
  geom_bar(aes(x = name, y = unit_price / 10000, fill = rarity), stat="identity") +
  geom_point(aes(x = name, y = vendor_value / 10000), fill = "#000000", stat="identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# render boxplot with outliers
item_list_sells %>% 
ggplot(aes(x = factor(rarity), y = unit_price / 10000, fill = factor(type))) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


